using System.Text;
using PgDeploy.Diff;
using PgDeploy.Schema;

namespace PgDeploy.Sql;

public sealed class MigrationSqlGenerator
{
    public string GenerateCreateTable(TableDefinition table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- Create table {table.FullName}");
        sb.AppendLine($"CREATE TABLE {SqlName.Qualified(table.Schema, table.Name)} (");

        var definitions = new List<string>();
        foreach (var column in table.Columns.OrderBy(x => x.OrdinalPosition))
            definitions.Add("    " + ColumnSql(column));

        if (table.PrimaryKey is not null && table.PrimaryKey.Columns.Count > 0)
        {
            var pkColumns = string.Join(", ", table.PrimaryKey.Columns.Select(SqlName.Quote));
            definitions.Add($"    CONSTRAINT {SqlName.Quote(table.PrimaryKey.Name)} PRIMARY KEY ({pkColumns})");
        }

        sb.AppendLine(string.Join("," + Environment.NewLine, definitions));
        sb.AppendLine(");");
        return sb.ToString();
    }

    public string GenerateAddColumn(TableDefinition table, ColumnDefinition column)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- Add column {table.FullName}.{column.Name}");
        sb.AppendLine($"ALTER TABLE {SqlName.Qualified(table.Schema, table.Name)}");
        sb.AppendLine($"    ADD COLUMN {ColumnSql(column)};");
        return sb.ToString();
    }

    public string GenerateAlterColumn(TableDefinition table, ColumnChange change)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- Alter column {table.FullName}.{change.SourceColumn.Name}");

        foreach (var kind in change.Changes)
        {
            switch (kind)
            {
                case ColumnChangeKind.TypeChanged:
                    sb.AppendLine($"ALTER TABLE {SqlName.Qualified(table.Schema, table.Name)}");
                    sb.AppendLine($"    ALTER COLUMN {SqlName.Quote(change.SourceColumn.Name)} TYPE {change.SourceColumn.FormattedType};");
                    sb.AppendLine();
                    break;

                case ColumnChangeKind.NullabilityChanged:
                    sb.AppendLine($"ALTER TABLE {SqlName.Qualified(table.Schema, table.Name)}");
                    sb.AppendLine(change.SourceColumn.IsNullable
                        ? $"    ALTER COLUMN {SqlName.Quote(change.SourceColumn.Name)} DROP NOT NULL;"
                        : $"    ALTER COLUMN {SqlName.Quote(change.SourceColumn.Name)} SET NOT NULL;");
                    sb.AppendLine();
                    break;

                case ColumnChangeKind.DefaultChanged:
                    sb.AppendLine($"ALTER TABLE {SqlName.Qualified(table.Schema, table.Name)}");
                    if (string.IsNullOrWhiteSpace(change.SourceColumn.DefaultValue))
                        sb.AppendLine($"    ALTER COLUMN {SqlName.Quote(change.SourceColumn.Name)} DROP DEFAULT;");
                    else
                        sb.AppendLine($"    ALTER COLUMN {SqlName.Quote(change.SourceColumn.Name)} SET DEFAULT {change.SourceColumn.DefaultValue};");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString();
    }

    public string GenerateFullMigration(SchemaDiff diff)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by PgDeploy");
        sb.AppendLine($"-- Created at: {DateTimeOffset.UtcNow:O}");
        sb.AppendLine();

        foreach (var table in diff.AddedTables)
        {
            sb.AppendLine(GenerateCreateTable(table));
        }

        foreach (var tableChange in diff.ChangedTables)
        {
            foreach (var column in tableChange.AddedColumns)
                sb.AppendLine(GenerateAddColumn(tableChange.SourceTable, column));

            foreach (var columnChange in tableChange.ChangedColumns)
                sb.AppendLine(GenerateAlterColumn(tableChange.SourceTable, columnChange));
        }

        return sb.ToString();
    }

    private static string ColumnSql(ColumnDefinition column)
    {
        var sb = new StringBuilder();
        sb.Append($"{SqlName.Quote(column.Name)} {column.FormattedType}");
        if (!string.IsNullOrWhiteSpace(column.DefaultValue))
            sb.Append($" DEFAULT {column.DefaultValue}");
        if (!column.IsNullable)
            sb.Append(" NOT NULL");
        return sb.ToString();
    }
}
